### ISSUE TITLE
Summary over several days

### ISSUE THREAD

**Issue by MrCustomizer** [codicelq/mytime#1]
First off: I very much like your Markdown-approach for time tracking. I would very much like to use it at work. There is one feature missing for it being suitable for that, though.

What I need at work is a summary over several days, typically the five workdays from Monday to Friday (but not always). I've tried running a summary over more than one day and it kind of works, when the sum of hours for every task and for "Total" does not exceed 24 hours. If it exceeds 24 hours, it just starts counting at zero again.

There is also a minor misbehaviour regarding the counting of invalid entries, which is probably caused by the titles of the weekdays. Fixing this is not very important to me, though.

Would you be willing to add support for adding up tasks over several days? Could also be useful for people, who want to have sum up bigger timespans, like months.

Let me know, if you need more information on this feature request.

Example:
```
## Monday 08 February
- `01:05` // _starting
- `10:02` Maintenance
- `10:15` Meeting
- `22:12` Maintenance

## Tuesday 09 February
- `02:05` // _starting
- `22:12` Maintenance

## Wednesday 10 February
- `03:05` // _starting
- `22:12` Maintenance

## Thursday 11 February
- `01:05` // _starting
- `22:12` Maintenance

## Friday 12 February

- `09:05` //_Let's start_
- `09:50` Chat
- `10:35` Maintenance
- `11:35` do stuff
- `12:05` Maintenance
- `21:29` do stuff

| Time span          | Task        |
| -----------------: | ----------- |
|          `00:45`   | Chat        |
|          `10:30`   | Maintenance |
|          `00:15`   | Meeting     |
|          `10:30`   | do stuff    |
|        **`21:45`** | **Total**   |

> _Last update 22:01_ / Lines [valid:12, comments:4, invalid:5]
```

**Comment by MrCustomizer** [comment]
I just found out that changing the setting Time Span Format to minutesOrHours solves this problem. Now only the the issue with the invalid lines remains, which is not important to me. Should I close this ticket or do you want me to keep it open for the invalid lines?

**Comment by codicelq** [comment]
> I just found out that changing the setting Time Span Format to minutesOrHours solves this problem. Now only the the issue with the invalid lines remains, which is not important to me. Should I close this ticket or do you want me to keep it open for the invalid lines?

I am glad the extension is useful to you, I removed the invalid counter from "last update" line.
